POST http://localhost:3333/subscriptions
Content-Type: application/json

{
    "name": "W_K.O",
    "email": "wko@wkodev.com"
}

###

GET http://localhost:3333/invites/8f5c478a-2ce2-4270-8e51-929dffd99e58

###

GET http://localhost:3333/subscribers/8f5c478a-2ce2-4270-8e51-929dffd99e58/ranking/clicks

###

GET http://localhost:3333/subscribers/8f5c478a-2ce2-4270-8e51-929dffd99e58/ranking/count

###

GET http://localhost:3333/subscribers/8f5c478a-2ce2-4270-8e51-929dffd99e58/ranking/position

###

GET http://localhost:3333/ranking

###
 
POST http://localhost:3333/messages
Content-Type: application/json

{
    "message": "Quais os e-mails dos usuários cadastrados em minha aplicação?"
}